# Generated by Django 3.1.3 on 2020-11-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=50)),
                ('entry_date', models.DateField(verbose_name='Joining Date')),
                ('exit_date', models.DateField()),
                ('time_percent', models.IntegerField(verbose_name='100 if Full Time')),
            ],
        ),
    ]
