# Generated by Django 3.1.3 on 2020-11-21 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AddField(
            model_name='person',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='entry_date',
            field=models.DateField(help_text='Joining Date'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ou_id', models.CharField(max_length=20, unique=True)),
                ('ou_name', models.CharField(max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.person')),
                ('parent_ou', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.orgunit')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='org_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.orgunit'),
        ),
    ]
