# Generated by Django 3.1.4 on 2020-12-17 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20201212_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_org_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='is_org_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalorgunit',
            name='delegate',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organization.employee'),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='delegate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ou_delegate', to='organization.employee'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ou_manager', to='organization.employee'),
        ),
    ]
