# Generated by Django 3.1.4 on 2020-12-24 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0008_auto_20201217_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='org',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='org_unit',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.orgunit'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='org',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='org_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organization.orgunit'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='supervisor',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organization.employee'),
        ),
        migrations.AlterField(
            model_name='historicalorgunit',
            name='delegate',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organization.employee'),
        ),
        migrations.AlterField(
            model_name='historicalorgunit',
            name='manager',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organization.employee'),
        ),
        migrations.AlterField(
            model_name='historicalorgunit',
            name='org',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='historicalorgunit',
            name='parent_ou',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organization.orgunit'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='delegate',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ou_delegate', to='organization.employee'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ou_manager', to='organization.employee'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='org',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='parent_ou',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.orgunit'),
        ),
        migrations.CreateModel(
            name='OrgDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('EC', 'Employee Category'), ('JG', 'Job Grade')], max_length=2)),
                ('value', models.CharField(max_length=50)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'unique_together': {('field', 'value')},
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='category',
            field=models.ForeignKey(limit_choices_to={'field': 'EC'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emp_category', to='organization.orgdesign'),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_grade',
            field=models.ForeignKey(limit_choices_to={'field': 'JG'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emp_grade', to='organization.orgdesign'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'field': 'EC'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organization.orgdesign'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='job_grade',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'field': 'JG'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organization.orgdesign'),
        ),
    ]
