# Generated by Django 3.1.4 on 2020-12-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_auto_20201224_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='entry_date',
            field=models.DateField(help_text='Joining Date', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='exit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='entry_date',
            field=models.DateField(help_text='Joining Date', null=True),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='exit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
